var Point=function(){function c(a,d,b){void 0===b&&(b=-1);this.angle=0;this.x=a;this.y=d;this.i=b}c.prototype.getX=function(){return this.x};c.prototype.getY=function(){return this.y};c.prototype.getI=function(){return this.i};c.prototype.getAngle=function(){return this.angle};c.prototype.setAngle=function(a){this.angle=a;return this};return c}(),Canvas=function(){function c(a,d){this.canvas=a;this.padding=d;this.width=a.width();this.height=a.height()}c.prototype.getWidth=function(){return this.width};
c.prototype.getHeight=function(){return this.height};c.prototype.getPadding=function(){return this.padding};c.prototype.drawPoints=function(a){this.canvas.removeLayers().clearCanvas();for(var d=0,b=a.length;d<b;d++)this.drawPoint(""+d,a[d],"#000","#777")};c.prototype.drawPoint=function(a,d,b,e){this.canvas.drawArc({radius:3,layer:!0,x:d.getX(),y:d.getY(),strokeWidth:1,groups:["point"],fillStyle:e,name:"point."+a,strokeStyle:b})};c.prototype.highlightPoint=function(a,d,b){this.canvas.removeLayer("point."+
a.getI());this.drawPoint(""+a.getI(),a,d,b)};c.prototype.drawPolygon=function(a,d,b){this.canvas.removeLayerGroup("polygon");for(var e=0,c=a.length;e<c;e++)this.highlightPoint(a[e],d,b),this.canvas.drawLine({layer:!0,strokeWidth:2,strokeStyle:b,groups:["polygon"],name:"polygonLine."+e,x1:a[e].getX(),y1:a[e].getY(),x2:a[(e+1)%c].getX(),y2:a[(e+1)%c].getY()})};c.prototype.operationCountInfo=function(a,d,b){this.canvas.drawText({x:10,y:428,layer:!0,fontSize:12,align:"left",fillStyle:"#777",fromCenter:!1,
name:"operationCount",text:a+" operations in "+d+"ms ("+b+")"})};c.prototype.clearSolution=function(){this.canvas.removeLayerGroup("polygon").removeLayer("operationCount").setLayerGroup("point",{fillStyle:"#777",strokeStyle:"#000"}).drawLayers()};return c}(),Controls=function(){function c(){}c.prototype.getPointCount=function(){return parseInt(this.pointCountSlider.val())};return c}(),Result=function(){function c(){this.counter=0;this.polygon=[]}c.prototype.count=function(a){void 0===a&&(a=1);this.counter+=
a};c.prototype.getCounter=function(){return this.counter};c.prototype.addVertex=function(a){this.polygon.push(a);return this};c.prototype.getPolygon=function(){return this.polygon};c.prototype.sortPolygon=function(){this.polygon=Helpers.sortConvexPolygon(this.polygon);return this};return c}(),Helpers=function(){function c(){}c.sortConvexPolygon=function(a){for(var d=this.findCentroid(a),b=0,e=a.length;b<e;b++)a[b].setAngle(Math.atan2(a[b].getY()-d.getY(),a[b].getX()-d.getX()));a.sort(function(a,b){return a.getAngle()-
b.getAngle()});return a};c.findCentroid=function(a){for(var d=0,b=0,e=0,c=a.length;e<c;e++)d+=a[e].getX(),b+=a[e].getY();return new Point(d/c,b/c)};c.laysPointInTriangle=function(a,d,b,e){return 0>=(b.getY()-d.getY())*(d.getX()-a.getX())+(d.getX()-b.getX())*(d.getY()-a.getY())&&0>=(e.getY()-b.getY())*(b.getX()-a.getX())+(b.getX()-e.getX())*(b.getY()-a.getY())&&0>=(d.getY()-e.getY())*(e.getX()-a.getX())+(e.getX()-d.getX())*(e.getY()-a.getY())};c.findExtremes=function(a){for(var d=null,b=null,e=0,c=
a.length;e<c;e++){if(null===d||a[e].getX()<d.getX())d=a[e];if(null===b||a[e].getX()>b.getX())b=a[e]}return{min:d,max:b}};c.vectorsAngle=function(a,d){return Math.atan2(a[0]*d[1]-d[0]*a[1],a[0]*d[0]+a[1]*d[1])};c.findFarthestPointFromLineToTheLeft=function(a,d,b){for(var e=null,g=null,f=0,h=b.length;f<h;f++)if(b[f]!==a&&b[f]!==d&&c.isPointToTheLeftFromLine(b[f],a,d)){var k=c.pointFromLineDistance(b[f],a,d);if(null===g||k>g)e=b[f],g=k}return e};c.splitPointsByTriangle=function(a,d,b,e){for(var g=[[],
[]],f=0,h=e.length;f<h;f++)e[f]!==a&&e[f]!==d&&e[f]!==b&&(c.laysPointInTriangle(e[f],a,d,b)||(c.isPointToTheLeftFromLine(e[f],a,b)?g[0].push(e[f]):c.isPointToTheLeftFromLine(e[f],b,d)&&g[1].push(e[f])));return g};c.isPointToTheLeftFromLine=function(a,d,b){return 0>(b.getX()-d.getX())*(a.getY()-d.getY())-(b.getY()-d.getY())*(a.getX()-d.getX())};c.pointFromLineDistance=function(a,d,b){var e=b.getX()-d.getX(),c=b.getY()-d.getY();return Math.abs(c*a.getX()-e*a.getY()+b.getX()*d.getY())/Math.sqrt(e*e+
c*c)};return c}(),ConvexHull=function(){function c(){}c.quickHull=function(a,d){var b=Helpers.findExtremes(a),e=b.min,b=b.max;d.count(a.length);d.addVertex(e);d.addVertex(b);c._quickHull(e,b,a,d);c._quickHull(b,e,a,d);d.sortPolygon()};c._quickHull=function(a,d,b,e){if(b.length){var g=Helpers.findFarthestPointFromLineToTheLeft(a,d,b);e.addVertex(g);e.count(b.length);var f=Helpers.splitPointsByTriangle(a,d,g,b);e.count(b.length);c._quickHull(a,g,f[0],e);c._quickHull(g,d,f[1],e)}};c.giftWrapping=function(a,
d){var b=Helpers.findExtremes(a).max,e=b,c=[0,-1];do{d.count();d.addVertex(e);for(var f=null,h=null,k=null,l=0,p=a.length;l<p;l++)if(a[l]!==e){d.count();var m=[a[l].getX()-e.getX(),a[l].getY()-e.getY()],n=Helpers.vectorsAngle(c,m);if(null===f||n<f)f=n,h=m,k=a[l]}c=h;e=k}while(e!==b)};c.primitive=function(a,d){for(var b=a.length,e=0;e<b;e++){for(var c=!0,f=0;c&&f<b;f++)if(e!==f)for(var h=0;c&&h<b;h++)if(e!==h&&f!==h)for(var k=0;c&&k<b;k++)e!==k&&f!==k&&h!==k&&(d.count(),Helpers.laysPointInTriangle(a[e],
a[f],a[h],a[k])&&(c=!1));c&&d.addVertex(a[e])}d.sortPolygon()};return c}(),Program=function(){function c(a,d){this.points=[];this.canvas=a;this.controls=d}c.prototype.run=function(){var a=this;a.controls.pointCountInfo.text(a.controls.getPointCount());this.controls.pointCountSlider.on("input change",function(b){a.controls.pointCountInfo.text(a.controls.getPointCount())});for(var d=this.getAlgButtons(),b=0,c=d.length;b<c;b++)d[b].on("click",function(b){a.setAlgButtonsDisabled(!0);a.controls.clearButton.attr("disabled",
null)});this.controls.generatorButton.on("click",function(b){a.generatePoints(a.controls.getPointCount());a.canvas.drawPoints(a.points);a.setAlgButtonsDisabled(!1);a.controls.clearButton.attr("disabled",!0)});this.controls.quickHullButton.on("click",function(b){a.runAlgorithm(ConvexHull.quickHull,"quick hull")});this.controls.giftWrappingButton.on("click",function(b){a.runAlgorithm(ConvexHull.giftWrapping,"gift wrapping")});this.controls.primitiveButton.on("click",function(b){a.runAlgorithm(ConvexHull.primitive,
"primitive")});this.controls.clearButton.on("click",function(b){a.canvas.clearSolution();a.setAlgButtonsDisabled(!1);a.controls.clearButton.attr("disabled",!0)})};c.prototype.generatePoints=function(a){for(this.points=[];this.points.length<a;){for(var d=!1,b=this.canvas.getPadding()+Math.floor((this.canvas.getWidth()-2*this.canvas.getPadding())*Math.random()),c=this.canvas.getPadding()+Math.floor((this.canvas.getHeight()-2*this.canvas.getPadding())*Math.random()),g=0,f=this.points.length;g<f;g++)if(this.points[g].getX()===
b||this.points[g].getY()===c){d=!0;break}d||this.points.push(new Point(b,c,g))}};c.prototype.runAlgorithm=function(a,d){var b=new Result,c=(new Date).getTime();a(this.points,b);c=(new Date).getTime()-c;this.canvas.drawPolygon(b.getPolygon(),"#44f","#99f");this.canvas.operationCountInfo(b.getCounter(),c,d)};c.prototype.setAlgButtonsDisabled=function(a){void 0===a&&(a=!0);for(var c=this.getAlgButtons(),b=0,e=c.length;b<e;b++)c[b].attr("disabled",a?!0:null)};c.prototype.getAlgButtons=function(){return[this.controls.quickHullButton,
this.controls.giftWrappingButton,this.controls.primitiveButton]};return c}();(function(c,a){var d=new Canvas(a("#canvas"),50),b=new Controls;b.pointCountSlider=a("#point-count");b.pointCountInfo=a("#point-count-info");b.generatorButton=a("#generate");b.quickHullButton=a("#alg-quick-hull");b.giftWrappingButton=a("#alg-gift-wrapping");b.primitiveButton=a("#alg-primitive");b.clearButton=a("#clear");(new Program(d,b)).run()})(window,window.jQuery);
