var Point=function(){return function(e,a,b){void 0===b&&(b=-1);this.x=e;this.y=a;this.i=b;this.angle=0}}(),Canvas=function(){function e(a,b){this.canvas=a;this.padding=b;this.width=a.width();this.height=a.height()}e.prototype.drawPoints=function(a){this.canvas.removeLayers().clearCanvas();for(var b=0,c=a.length;b<c;b++)this.drawPoint(""+b,a[b],"#000","#777")};e.prototype.drawPoint=function(a,b,c,d){this.canvas.drawArc({x:b.x,y:b.y,radius:3,layer:!0,strokeWidth:1,groups:["point"],fillStyle:d,name:"point."+
a,strokeStyle:c})};e.prototype.highlightPoint=function(a,b,c){this.canvas.removeLayer("point."+a.i);this.drawPoint(""+a.i,a,b,c)};e.prototype.drawPolygon=function(a,b,c){this.canvas.removeLayerGroup("polygon");for(var d=0,g=a.length;d<g;d++)this.highlightPoint(a[d],b,c),this.canvas.drawLine({layer:!0,strokeWidth:2,strokeStyle:c,groups:["polygon"],name:"polygonLine."+d,x1:a[d].x,y1:a[d].y,x2:a[(d+1)%g].x,y2:a[(d+1)%g].y})};e.prototype.operationCountInfo=function(a,b,c){this.canvas.drawText({x:10,y:428,
layer:!0,fontSize:12,align:"left",fillStyle:"#777",fromCenter:!1,name:"operationCount",text:a+" operations in "+b+"ms ("+c+")"})};e.prototype.clearSolution=function(){this.canvas.removeLayerGroup("polygon").removeLayer("operationCount").setLayerGroup("point",{fillStyle:"#777",strokeStyle:"#000"}).drawLayers()};return e}(),Controls=function(){function e(){}e.prototype.getPointCount=function(){return parseInt(this.pointCountSlider.val())};return e}(),Helpers=function(){function e(){}e.sortConvexPolygon=
function(a){for(var b=this.findCentroid(a),c=0,d=a.length;c<d;c++)a[c].angle=Math.atan2(a[c].y-b.y,a[c].x-b.x);a.sort(function(a,b){return a.angle-b.angle});return a};e.findCentroid=function(a){for(var b=new Point(0,0),c=0,d=a.length;c<d;c++)b.x+=a[c].x,b.y+=a[c].y;b.x/=d;b.y/=d;return b};e.laysPointInTriangle=function(a,b,c,d){return 0>=(c.y-b.y)*(b.x-a.x)+(b.x-c.x)*(b.y-a.y)&&0>=(d.y-c.y)*(c.x-a.x)+(c.x-d.x)*(c.y-a.y)&&0>=(b.y-d.y)*(d.x-a.x)+(d.x-b.x)*(d.y-a.y)};e.findExtremes=function(a){for(var b=
null,c=null,d=0,g=a.length;d<g;d++){if(null===b||a[d].x<b.x)b=a[d];if(null===c||a[d].x>c.x)c=a[d]}return{min:b,max:c}};e.vectorsAngle=function(a,b){return Math.atan2(a[0]*b[1]-b[0]*a[1],a[0]*b[0]+a[1]*b[1])};e.findFarthestPointFromLineToTheLeft=function(a,b,c){for(var d=null,g=null,f=0,k=c.length;f<k;f++)if(c[f]!==a&&c[f]!==b&&e.isPointToTheLeftFromLine(c[f],a,b)){var h=e.pointFromLineDistance(c[f],a,b);if(null===g||h>g)d=c[f],g=h}return d};e.splitPointsByTriangle=function(a,b,c,d){for(var g=[[],
[]],f=0,k=d.length;f<k;f++)d[f]!==a&&d[f]!==b&&d[f]!==c&&(e.laysPointInTriangle(d[f],a,b,c)||(e.isPointToTheLeftFromLine(d[f],a,c)?g[0].push(d[f]):e.isPointToTheLeftFromLine(d[f],c,b)&&g[1].push(d[f])));return g};e.isPointToTheLeftFromLine=function(a,b,c){return 0>(c.x-b.x)*(a.y-b.y)-(c.y-b.y)*(a.x-b.x)};e.pointFromLineDistance=function(a,b,c){var d=c.x-b.x,g=c.y-b.y;return Math.abs(g*a.x-d*a.y+c.x*b.y)/Math.sqrt(d*d+g*g)};return e}(),ConvexHull=function(){function e(){}e.quickHull=function(a,b){var c=
Helpers.findExtremes(a),d=c.min,c=c.max;b.counter+=a.length;b.polygon.push(d);b.polygon.push(c);e._quickHull(d,c,a,b);e._quickHull(c,d,a,b);b.polygon=Helpers.sortConvexPolygon(b.polygon)};e._quickHull=function(a,b,c,d){if(c.length){var g=Helpers.findFarthestPointFromLineToTheLeft(a,b,c);d.counter+=c.length;d.polygon.push(g);for(var f=[],k=[],h=0,l=c.length;h<l;h++)c[h]!==a&&c[h]!==b&&c[h]!==g&&(d.counter++,Helpers.laysPointInTriangle(c[h],a,b,g)||(Helpers.isPointToTheLeftFromLine(c[h],a,g)?f.push(c[h]):
Helpers.isPointToTheLeftFromLine(c[h],g,b)&&k.push(c[h])));f=Helpers.splitPointsByTriangle(a,b,g,c);d.counter+=c.length;e._quickHull(a,g,f[0],d);e._quickHull(g,b,f[1],d)}};e.giftWrapping=function(a,b){var c=Helpers.findExtremes(a).max,d=c,g=[0,-1];do{b.counter++;b.polygon.push(d);for(var e=null,k=null,h=null,l=0,p=a.length;l<p;l++)if(a[l]!==d){b.counter++;var m=[a[l].x-d.x,a[l].y-d.y],n=Helpers.vectorsAngle(g,m);if(null===e||n<e)e=n,k=m,h=a[l]}g=k;d=h}while(d!==c)};e.primitive=function(a,b){for(var c=
a.length,d=0;d<c;d++){for(var e=!0,f=0;e&&f<c;f++)if(d!==f)for(var k=0;e&&k<c;k++)if(d!==k&&f!==k)for(var h=0;e&&h<c;h++)d!==h&&f!==h&&k!==h&&(b.counter++,Helpers.laysPointInTriangle(a[d],a[f],a[k],a[h])&&(e=!1));e&&b.polygon.push(a[d])}b.polygon=Helpers.sortConvexPolygon(b.polygon)};return e}(),Program=function(){function e(a,b){this.canvas=a;this.controls=b}e.prototype.run=function(){var a=this;a.controls.pointCountInfo.text(a.controls.getPointCount());this.controls.pointCountSlider.on("input change",
function(b){a.controls.pointCountInfo.text(a.controls.getPointCount())});for(var b=this.getAlgButtons(),c=0,d=b.length;c<d;c++)b[c].on("click",function(b){a.setAlgButtonsDisabled(!0);a.controls.clearButton.attr("disabled",null)});this.controls.generatorButton.on("click",function(b){a.generatePoints(a.controls.getPointCount());a.canvas.drawPoints(a.points);a.setAlgButtonsDisabled(!1);a.controls.clearButton.attr("disabled",!0)});this.controls.quickHullButton.on("click",function(b){a.runAlgorithm(ConvexHull.quickHull,
"quick hull")});this.controls.giftWrappingButton.on("click",function(b){a.runAlgorithm(ConvexHull.giftWrapping,"gift wrapping")});this.controls.primitiveButton.on("click",function(b){a.runAlgorithm(ConvexHull.primitive,"primitive")});this.controls.clearButton.on("click",function(b){a.canvas.clearSolution();a.setAlgButtonsDisabled(!1);a.controls.clearButton.attr("disabled",!0)})};e.prototype.generatePoints=function(a){for(this.points=[];this.points.length<a;){for(var b=!1,c=this.canvas.padding+Math.floor((this.canvas.width-
2*this.canvas.padding)*Math.random()),d=this.canvas.padding+Math.floor((this.canvas.height-2*this.canvas.padding)*Math.random()),e=0,f=this.points.length;e<f;e++)if(this.points[e].x===c||this.points[e].y===d){b=!0;break}b||this.points.push(new Point(c,d,e))}};e.prototype.runAlgorithm=function(a,b){var c={counter:0,polygon:[]},d=(new Date).getTime();a(this.points,c);d=(new Date).getTime()-d;this.canvas.drawPolygon(c.polygon,"#44f","#99f");this.canvas.operationCountInfo(c.counter,d,b)};e.prototype.setAlgButtonsDisabled=
function(a){void 0===a&&(a=!0);for(var b=this.getAlgButtons(),c=0,d=b.length;c<d;c++)b[c].attr("disabled",a?!0:null)};e.prototype.getAlgButtons=function(){return[this.controls.quickHullButton,this.controls.giftWrappingButton,this.controls.primitiveButton]};return e}();
(function(e,a){var b=new Canvas(a("#canvas"),50),c=new Controls;c.pointCountSlider=a("#point-count");c.pointCountInfo=a("#point-count-info");c.generatorButton=a("#generate");c.quickHullButton=a("#alg-quick-hull");c.giftWrappingButton=a("#alg-gift-wrapping");c.primitiveButton=a("#alg-primitive");c.clearButton=a("#clear");(new Program(b,c)).run()})(window,window.jQuery);
